# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedredirector', '0002_auto_20160915_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribedfeed',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedredirector.Feed'),
        ),
        migrations.AddField(
            model_name='subscribedfeed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedredirector.User'),
        ),
    ]
