# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedredirector', '0003_auto_20160915_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticleCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='userarticlecount',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedredirector.Article'),
        ),
        migrations.AddField(
            model_name='userarticlecount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedredirector.User'),
        ),
        migrations.AlterUniqueTogether(
            name='userarticlecount',
            unique_together=set([('article', 'user')]),
        ),
    ]
